# substitutions:
#   _IMAGE_TAG: 'latest'

steps:

# # use Buildpacks to create a container image
# - name: 'gcr.io/k8s-skaffold/pack'
#   dir: './'
#   entrypoint: 'pack'
#   args:
#     [
#       'build', '--builder=gcr.io/buildpacks/builder', '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${REPO_NAME}-${BRANCH_NAME}-frontend:${_IMAGE_TAG}',
#       '--env', 'NEXT_PUBLIC_URL_BACKEND=$(gcloud run services describe $REPO_NAME-$BRANCH_NAME-backend --region $LOCATION --format "value(status.url)")',
#       '--env',  'NEXT_PUBLIC_ENV=${_ENV}'
#     ]

# #pushing to artifact registry
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push',  '${LOCATION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${REPO_NAME}-${BRANCH_NAME}-frontend:${_IMAGE_TAG}']

# STEP1: Push to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [
      'run', 'deploy', '${REPO_NAME}-${BRANCH_NAME}-frontend',
      '--source', '.',
      '--region', '${LOCATION}', '--platform', 'managed', '--allow-unauthenticated',
      '--update-secrets', 'GOOGLE_CLIENT=google-client-secret:latest, AUTH_SECRET=AUTH_SECRET:latest', 
      '--update-env-vars',  'PROJECT_ID=${PROJECT_ID}',
      '--update-env-vars', 'NEXT_PUBLIC_ENV=${_ENV}',
      # '--verbosity', 'debug'
    ]

# STEP2: Update Auth URL
- id: 'release'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      gcloud run deploy ${REPO_NAME}-${BRANCH_NAME}-frontend \
        --region ${LOCATION} --platform managed --allow-unauthenticated  \
        --image ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/${REPO_NAME}-${BRANCH_NAME}-frontend \
        --update-env-vars AUTH_URL=$(gcloud run services describe $REPO_NAME-$BRANCH_NAME-frontend --region $LOCATION --format "value(status.url)")/api/auth \
        --update-env-vars NEXT_PUBLIC_URL_BACKEND=$(gcloud run services describe $REPO_NAME-$BRANCH_NAME-backend --region $LOCATION --format "value(status.url)") \


# STEP3: Verify environment variables have been correctly set
- id: 'verify_env_vars'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      gcloud run services describe ${REPO_NAME}-${BRANCH_NAME}-frontend \
        --region ${LOCATION} --platform managed --format "value(spec.template.spec.containers[0].env)"